-- =============================================================================
-- Migration 002: Add Public UID Columns (ULID) to users, wallets, transactions
-- =============================================================================
-- Keeps the auto-increment BIGINT as the internal PRIMARY KEY / FK target,
-- and adds a public, non-sequential `uid` used in API responses so clients
-- never have to guess or enumerate row IDs.
--
-- New rows get a 26-char Crockford-base32 ULID generated by the application.
-- Existing rows are backfilled with a 32-char hex UUID so the column stays
-- NOT NULL and UNIQUE without a default value.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. users
-- -----------------------------------------------------------------------------
ALTER TABLE users
    ADD COLUMN uid VARCHAR(32) NULL AFTER id;

UPDATE users SET uid = REPLACE(UUID(), '-', '') WHERE uid IS NULL;

ALTER TABLE users
    MODIFY COLUMN uid VARCHAR(32) NOT NULL,
    ADD UNIQUE KEY uq_users_uid (uid);

-- -----------------------------------------------------------------------------
-- 2. wallets
-- -----------------------------------------------------------------------------
ALTER TABLE wallets
    ADD COLUMN uid VARCHAR(32) NULL AFTER id;

UPDATE wallets SET uid = REPLACE(UUID(), '-', '') WHERE uid IS NULL;

ALTER TABLE wallets
    MODIFY COLUMN uid VARCHAR(32) NOT NULL,
    ADD UNIQUE KEY uq_wallets_uid (uid);

-- -----------------------------------------------------------------------------
-- 3. transactions
-- -----------------------------------------------------------------------------
ALTER TABLE transactions
    ADD COLUMN uid VARCHAR(32) NULL AFTER id;

UPDATE transactions SET uid = REPLACE(UUID(), '-', '') WHERE uid IS NULL;

ALTER TABLE transactions
    MODIFY COLUMN uid VARCHAR(32) NOT NULL,
    ADD UNIQUE KEY uq_transactions_uid (uid);